name: robotics
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-version=12.4=hbda6634_3
  - cudnn=9.1.1.17=cuda12_1
  - ld_impl_linux-64=2.44=h153f514_2
  - libcublas=12.4.5.8=h99ab3db_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.12=h955ad1f_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - ale-py==0.11.2
      - annotated-types==0.7.0
      - anyio==4.11.0
      - astunparse==1.6.3
      - attrs==25.4.0
      - cachetools==6.2.1
      - cattrs==1.5.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpickle==3.1.1
      - contourpy==1.2.1
      - cycler==0.12.1
      - exceptiongroup==1.3.0
      - farama-notifications==0.0.4
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.42.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.48.2
      - gym==0.26.2
      - gym-notices==0.1.0
      - gymnasium==1.2.1
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.0.1
      - idna==3.11
      - jinja2==3.1.6
      - keras==2.8.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mlagents-envs==1.0.0
      - mpmath==1.3.0
      - namex==0.1.0
      - networkx==3.4.2
      - numpy==1.21.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - optree==0.17.0
      - packaging==25.0
      - pandas==2.0.3
      - pettingzoo==1.15.0
      - pillow==12.0.0
      - pip==25.3
      - platformdirs==4.5.0
      - protobuf==3.19.0
      - psutil==7.1.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pygame==2.6.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - rsa==4.9.1
      - sentry-sdk==2.42.1
      - setuptools==80.9.0
      - shellingham==1.5.4
      - shimmy==2.0.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - stable-baselines3==2.7.0
      - sympy==1.14.0
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.8.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.2.0
      - tf-estimator-nightly==2.8.0.dev2021122109
      - torch==2.9.0
      - tqdm==4.67.1
      - triton==3.5.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.22.2
      - werkzeug==3.1.3
      - wrapt==2.0.0
prefix: /home/matteo/anaconda3/envs/robotics
